---
# vars file for satellite-validate

# Min Size of Data Device in GB
min_data_device_size: 200

# Min Sizes of Mounts in GB
min_partition_sizes:
  - name: root
    path: /
    size: 10
    optional: no
    os: yes
  - name: boot
    path: /boot
    # `lsblk` reports size in MB for /boot
    size: 1000
    optional: no
    os: yes
  - name: home
    path: /home
    size: 5
    optional: no
    os: yes
  - name: usr
    path: /usr
    size: 5
    optional: no
    os: yes
  - name: var
    path: /var
    size: 5
    optional: no
    os: yes
  - name: var_log
    path: /var/log
    size: 5
    optional: no
    os: yes
  - name: var_log_audit
    path: /var/log/audit
    size: 5
    optional: no
    os: yes
  - name: var_lib_pulp
    path: /var/lib/pulp
    size: 120
    optional: no
    os: no
  - name: var_lib_mongodb
    path: /var/lib/mongodb
    size: 50
    optional: no
    os: no
  - name: var_lib_pgsql
    path: /var/lib/pgsql
    size: 10
    optional: no
    os: no
  - name: opt
    path: /opt
    size: 3
    optional: yes
    os: no
  - name: var_cache_pulp
    path: /var/cache/pulp
    size: 30
    optional: yes
    os: no
  
selinux_state1: []
selinux_state2: []