---
- name: Install Common Packages (Ubuntu)
  become: yes
  become_user: root
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - curl 
    - xclip
  when: 
    - ansible_distribution == "Ubuntu"

- name: Install ZSH (Ubuntu)
  become: yes
  become_user: root
  apt:
    name: zsh
    state: latest
  when: 
    - ansible_distribution == "Ubuntu"
    - component_zsh
