---
- include: update_system.yml
- include: install_packages.yml
- include: common_directories.yml
- include: flatpak.yml
  when:
    - component_flatpak
- include: pip.yml
  when:
    - component_pip
- include: snap.yml
  when:
    - component_snap
- include: npm.yml
  when:
    - component_npm

- include: kubuntu_backports.yml
  when: 
    - ansible_distribution == "Ubuntu"
    - component_gui
    - gui_kde or component_kubuntu_backports
