---
- name: Install npm (Ubuntu)
  become: yes
  become_user: root
  apt:
    name: npm
    state: latest
  when: 
    - ansible_distribution == "Ubuntu" 

# - name: Move NPM RC to user home dir
#   command: "cp /root/.npmrc /home/kevin"
#   args:
#     creates: "/home/kevin/.npmrc"

- name: Create NPM directory
  file:
    path: "/home/kevin/.npm-global"
    state: directory
    mode: 0755

- name: Set NPM prefix
  command: "npm config set prefix '/home/kevin/.npm-global'"

- name: Add NPM global dir to $PATH (ZSH)
  lineinfile:
    path: "/home/kevin/.zshrc"
    line: "export PATH=$HOME/.npm-global:$PATH"
  when:
    - component_zsh

- name: Source profile (ZSH)
  shell: "source /home/kevin/.zshrc"
  args:
    executable: /bin/bash
  when:
    - component_zsh

- name: Add NPM global dir to $PATH (FISH)
  lineinfile:
    path: "/home/kevin/.config/fish/config.fish"
    line: "set -gx PATH /home/kevin/.npm-global/bin $PATH"
  when:
    - component_fish

# Need to source fish profile?
