---
- name: Add Snapd (Fedora)
  become: yes
  become_user: root
  dnf:
    name: snapd
    state: latest
  when: 
    - ansible_distribution == "Fedora"

- name: Fix Links for Snapd (Fedora)
  become: yes
  become_user: root
  file:
    src: "/var/lib/snapd/snap"
    dest: "/snap"
    state: link
  when: 
    - ansible_distribution == "Fedora"