---
- name: update the system (Ubuntu)
  become: yes
  become_user: root
  apt:
    name: "*"
    state: latest
    update_cache: yes
  when: 
    - ansible_distribution == "Ubuntu"

- name: update the system (Fedora)
  become: yes
  become_user: root
  dnf:
    name: "*"
    state: latest
  when: 
    - ansible_distribution == "Fedora"
