---
- name: Install LXD (Ubuntu)
  become: yes
  become_user: root
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - lxd
    - lxd-client
  when: 
    - (ansible_distribution == "Ubuntu") 

- name: Append kevin to the lxd group
  become: yes
  become_user: root
  user:
    name: kevin
    groups: lxd
    append: yes
