---
- name: Download rustup installer-script
  get_url:
    url: https://sh.rustup.rs
    dest: /home/kevin/.tmp/rustup-install.sh
    mode: 0740

- name: Install rustup
  shell: "/home/kevin/.tmp/rustup-install.sh -y"
  become_user: kevin
  args:
    creates: /home/kevin/.cargo
    executable: sh

- name: Source the Cargo ENV files
  shell: source /home/kevin/.cargo/env
  args:
    executable: /bin/bash

- name: Add Rust to $PATH (FISH)
  lineinfile:
    path: "/home/kevin/.config/fish/config.fish"
    line: "set -gx PATH /home/kevin/.cargo/bin $PATH"
  when:
    - default_shell == "fish"
    - component_fish

- name: Add Rust to $PATH (ZSH)
  lineinfile:
    path: "/home/kevin/.zshrc"
    line: "export PATH=$HOME/.cargo/bin:$PATH"
  when:
    - default_shell == "zsh"
    - component_zsh

- name: Set Rust Default Toolchain to Nightly
  command: rustup default nightly

- name: Install the additional rust components
  command: "rustup component add {{ item }}"
  ignore_errors: yes
  with_items:
    - rustfmt
    - clippy
    - rls

- name: Install Required System Packages (Ubuntu)
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - libssl-dev
    - cmake
    - pkg-config
  when: 
    - ansible_distribution == "Ubuntu"
    - development_machine or development_component_rust_cargo_extras

# Maybe split these out?
- name: Install All Cargo Extras 
  command: "cargo install {{ item }}"
  with_items:
    - cargo-update 
    - cargo-outdated 
    - cargo-graph 
    - cargo-geiger 
    - cargo-tree 
    - cargo-modules 
    - cargo-edit 
    - cargo-count 
    - cargo-bloat 
    - cargo-cache 
    - ripgrep 
    - exa 
    - skim 
    - mdbook 
    - bat 
    - fd-find 
    - tokei 
    - clog-cli 
    - hexyl   
  when: 
    - component_rust_cargo_extras

# this will add the line over and over
- name: Copy Rust setting to ZSH profile
  shell: "cat /home/kevin/.dotfiles/zsh/addons/rust.zsh-addon >> /home/kevin/.zshrc"
  when: 
    - component_dotfiles
    - default_shell == "zsh"
    - component_zsh

- name: Clone ASCIInema repository
  git:
    repo: https://github.com/LegNeato/asciinema-rs
    dest: /home/kevin/.build/asciinema
  when:
    - component_asciinema

- name: Build the ASCIInema Project
  command: cargo build --release
  args:
    chdir: /home/kevin/.build/asciinema
    creates: /home/kevin/.build/asciinema/target/release/asciinema
  when:
    - component_asciinema

- name: Copy the ASCIInema binary to PATH 
  command: "cp /home/kevin/.build/asciinema/target/release/asciinema /home/kevin/.local/bin"
  args:
    creates: /home/kevin/.local/bin/asciinema
  when:
    - component_asciinema