---
- name: Install VIM (Ubuntu)
  become: yes
  become_user: root
  apt:
    name: vim
    state: latest
  when: 
    - ansible_distribution == "Ubuntu"
    - component_vim
# - name: Move Vim dirs to user home dir
#   command: "cp -r /root/.viminfo /home/kevin"
#   args:
#     creates: "/home/kevin/.viminfo"

- name: Copy vim settings from dotfiles
  command: "cp -r /home/kevin/.dotfiles/vim /home/kevin/.vim"
  args:
    creates: /home/kevin/.vim
  when: 
    - component_dotfiles

- name: Copy vimrc from dotfiles
  command: "cp /home/kevin/.vim/vimrc-linux /home/kevin/.vimrc"
  args:
    creates: /home/kevin/.vimrc

- name: Clone vim Vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim
    dest: /home/kevin/.vim/bundle/Vundle.vim

- name: Install vim Plugins
  command: "vim +PluginInstall +qall"
