---
- name: Install tilix (Ubuntu)
  apt:
    name: tilix
    state: latest
    update_cache: yes
  when: 
    - ansible_distribution == "Ubuntu"
    - component_gui
    - component_tilix

- name: Create symbolic link to fix tilix (Ubuntu)
  file:
    src: "/etc/profile.d/vte-2.91.sh"
    dest: "/etc/profile.d/vte.sh"
    state: link
  when: 
    - ansible_distribution == "Ubuntu"
    - component_gui
    - component_tilix

- name: Install mpv player (Ubuntu)
  apt:
    name: mpv
    state: latest
  when: 
    - ansible_distribution == "Ubuntu"
    - component_gui
    - component_mpv

- name: Install rtv (Ubuntu)
  apt:
    name: rtv
    state: latest
  when: 
    - ansible_distribution == "Ubuntu"
    - component_rtv

- name: Download and Install Keybase (Ubuntu)
  apt:
    deb: "https://prerelease.keybase.io/keybase_amd64.deb"
  when: 
    - ansible_distribution == "Ubuntu"
    - component_gui
    - component_keybase

- name: Install missing packages (Ubuntu)
  command: apt-get -y install -f
  when: 
    - ansible_distribution == "Ubuntu"
    - component_gui
    - component_keybase

- name: Install Discord (Flatpak)
  flatpak:
    name: com.discordapp.Discord
    state: present
  when: 
    - component_discord
    - component_flatpak
    - component_gui

- name: Install Slack (Flatpak)
  flatpak:
    name: com.slack.Slack
    state: present
  when: 
    - component_slack
    - component_gui
    - component_flatpak

- name: Install Signal (Flatpak)
  flatpak:
    name: org.signal.Signal
    state: present
  when: 
    - component_signal
    - component_gui
    - component_flatpak

- name: Install Telegram (Flatpak)
  flatpak:
    name: org.telegram.desktop
    state: present
  when: 
    - component_telegram
    - component_gui
    - component_flatpak

- name: Install Dropbox (Flatpak)
  flatpak:
    name: com.dropbox.Client
    state: present
  when: 
    - component_dropbox
    - component_gui
    - component_flatpak

- name: Install Mailspring (Snap)
  command: snap install mailspring --classic
  args:
    creates: /snap/mailspring
  when:
    - component_gui
    - component_mailspring
    - component_snap